### ISSUE TITLE
Better docs for how to call directly call APIs

### ISSUE THREAD

**Issue by jun-dao** [Datatamer/unify-client-python#30]
Can we have a docs that specify how to use python client call non-versioned APIs?

**Comment by alex-batchelor** [comment]
Those docs are hard to find and I would like example usage.

**Comment by nbateshaus** [comment]
This should be addressed by #44 (which fixes #43 ) - with this change, addressing APIs out from under /api/versioned/v1 just requires an absolute path in `endpoint`.

**Comment by along528** [comment]
I agree that the docs could be improved around this. The latest change to v3.0 changes the behavior mentioned here (https://tamr-unify-python-client.readthedocs.io/en/stable/user-guide/advanced-usage.html#custom-http-requests) around setting the base_path. 

A more specific example of using this with an existing endpoint instead of a fake endpoint ("some/specific/endpoint") would go a long way

**Comment by pcattori** [comment]
Proposed Acceptance Criteria:

- Replace [Custom HTTP Request](https://tamr-unify-python-client.readthedocs.io/en/stable/user-guide/advanced-usage.html#custom-http-requests) section of the docs with a "Calling unstable API endpoints" section.
- Add an entry to the [FAQ](https://tamr-unify-python-client.readthedocs.io/en/stable/user-guide/faq.html) for "How to call internal/unstable API endpoints?" linking to the docs^
